Repository andela/bad_ass-ah-frontend, pull requests merged in 2019-06, with the labels that each got.

#21 164489894 User should be able like and dislike articles.
  src/actions/article.js
  src/actions/types.js
  src/actions/voteArticle.js
  src/assets/css/main.css
  src/assets/scss/_article.scss
  src/components/articles/SingleArticle.js
  src/reducers/article.js
  src/reducers/index.js
  src/tests/actions/voteArticles.test.js
  src/tests/components/articles/SingleArticle.test.js
  src/tests/reducers/articles/Article.test.js
Labels: Done, Ready for Review

#23 #164489891 rate a particular article
  package.json
  src/App.js
  src/actions/index.js
  src/actions/login.js
  src/actions/rateArticle.js
  src/actions/types.js
  src/assets/Images/icons/star.svg
  src/assets/Images/spinner.svg
  src/assets/Images/spinner1.svg
  src/assets/css/main.css
  src/assets/scss/_article.scss
  src/assets/scss/_button.scss
  src/assets/scss/_config.scss
  src/assets/scss/_sections.scss
  src/assets/scss/_starRating.scss
  src/assets/scss/main.scss
  src/components/articles/SingleArticle.js
  src/components/articles/rating/Rating.js
  src/components/users/login/Login.js
  src/reducers/index.js
  src/reducers/login.js
  src/reducers/rateArticle.js
  src/tests/actions/rating.test.js
  src/tests/components/actions/login.test.js
  src/tests/components/rating/rating.test.js
  src/tests/components/reducers/login.test.js
  src/tests/components/users/login/Login.test.js
  src/tests/reducers/rating.test.js
Labels: Ready for Review

#27 #164489909 user reading stats
  package.json
  src/actions/article.js
  src/actions/index.js
  src/actions/readingStats.js
  src/actions/types.js
  src/assets/Images/icons/study.svg
  src/assets/css/main.css
  src/assets/scss/_readingStats.scss
  src/assets/scss/main.scss
  src/components/articles/SingleArticle.js
  src/components/users/authenticate/Authenticate.js
  src/components/users/profile/ViewProfile.js
  src/helpers/Config.js
  src/reducers/index.js
  src/reducers/readingStats.js
  src/tests/actions/readingStats.test.js
  src/tests/components/articles/SingleArticle.test.js
  src/tests/components/users/profile/ViewProfile.test.js
  src/tests/reducers/readingStats.test.js
Labels: Ready for Review

#28 #166266972 Update and delete comment
  src/actions/comment/comment.js
  src/actions/types.js
  src/assets/Images/icons/comment_option.svg
  src/components/articles/SingleArticle.js
  src/components/comment/CommentItem.js
  src/components/comment/CreateComment.scss
  src/components/comment/comments.js
  src/helpers/jsonConfig.js
  src/reducers/comment/comments.js
  src/tests/actions/comment/comment.test.js
  src/tests/components/articles/SingleArticle.test.js
  src/tests/components/comment/CommentForm.test.js
  src/tests/components/comment/CommentItem.test.js
  src/tests/reducers/comments/comments.test.js
Labels: Ready for Review

#33 #164489896 Share article via social media plate-forms
  package.json
  src/actions/comment/comment.js
  src/components/articles/SingleArticle.js
  src/components/articles/shareArticle/shareArticle.js
  src/components/articles/shareArticle/shareArticle.scss
  src/tests/components/articles/shareArticle/shareArticle.test.js
  src/tests/components/comment/Comments.test.js
  src/tests/reducers/comments/comments.test.js
Labels: Ready for Review

#29 #164489906 Highlight a particular text in article body
  package.json
  src/App.js
  src/actions/article.js
  src/actions/highlight.js
  src/actions/types.js
  src/actions/voteArticle.js
  src/assets/css/main.css
  src/assets/scss/_article.scss
  src/assets/scss/_commentPopover.scss
  src/assets/scss/_highlightPopover.scss
  src/assets/scss/_profile.scss
  src/assets/scss/_style.scss
  src/assets/scss/main.scss
  src/components/Index.js
  src/components/articles/SingleArticle.js
  src/components/comment/CreateComment.scss
  src/components/popovers/Comment.js
  src/components/popovers/Highlight.js
  src/components/users/profile/ViewProfile.js
  src/reducers/highlight.js
  src/reducers/index.js
  src/tests/App.test.js
  src/tests/actions/article.test.js
  src/tests/actions/highlight.test.js
  src/tests/actions/voteArticles.test.js
  src/tests/components/articles/Helper.test.js
  src/tests/components/articles/SingleArticle.test.js
  src/tests/components/popovers/Comment.test.js
  src/tests/components/popovers/Highlight.test.js
  src/tests/components/users/profile/ViewProfile.test.js
  src/tests/reducers/highlight.test.js
  src/tests/utils/markHighlightedtext.test.js
  src/utils/markHighlightedText.js
Labels: Ready for Review

#26 164489894 Allowing a user to signup
  src/actions/activateUser.js
  src/actions/registration.js
  src/actions/types.js
  src/assets/Images/success.png
  src/assets/css/main.css
  src/assets/scss/_activate.scss
  src/assets/scss/_popup.scss
  src/assets/scss/main.scss
  src/components/Index.js
  src/components/articles/SingleArticle.js
  src/components/articles/rating/Rating.js
  src/components/layouts/Navbar.js
  src/components/users/authenticate/Authenticate.js
  src/components/users/registration/ActivateUser.js
  src/components/users/registration/Popup.js
  src/components/users/registration/Registration.js
  src/reducers/activate.js
  src/reducers/index.js
  src/reducers/registration.js
  src/routes/routes.js
  src/tests/actions/activateUser.test.js
  src/tests/actions/registration.test.js
  src/tests/components/articles/SingleArticle.test.js
  src/tests/components/users/registration/activateUser.test.js
  src/tests/components/users/registration/popup.test.js
  src/tests/components/users/registration/registration.test.js
  src/tests/reducers/activate.test.js
  src/tests/reducers/registration.test.js
Labels: help wanted

#31 #164489908 Like and DisLike comment
  src/App.js
  src/actions/article.js
  src/actions/comment/comment.js
  src/actions/comment/voteComment.js
  src/actions/types.js
  src/components/articles/SingleArticle.js
  src/components/comment/CommentItem.js
  src/components/comment/CreateComment.scss
  src/components/comment/LikeComment.scss
  src/components/comment/VoteComment.js
  src/components/comment/commentForm.js
  src/components/comment/comments.js
  src/components/users/authenticate/Authenticate.js
  src/components/users/login/Login.js
  src/helpers/Article.js
  src/helpers/Config.js
  src/helpers/jsonConfig.js
  src/reducers/comment/comments.js
  src/routes/routes.js
  src/tests/actions/comment/votecomment.test.js
  src/tests/components/comment/VoteComent.test.js
  src/tests/reducers/comments/comments.test.js
Labels: WIP

#40 #164489901 article reading time
  package.json
  src/assets/css/main.css
  src/assets/scss/_config.scss
  src/assets/scss/_style.scss
  src/components/articles/SingleArticle.js
Labels: Ready for Review

#37 #164489898 view notifications
  src/App.js
  src/actions/notification.js
  src/actions/types.js
  src/assets/css/main.css
  src/assets/scss/_highlightPopover.scss
  src/assets/scss/_navbar.scss
  src/assets/scss/_style.scss
  src/components/articles/SingleArticle.js
  src/components/layouts/Navbar.js
  src/reducers/index.js
  src/reducers/notification.js
  src/tests/actions/notification.test.js
  src/tests/components/layouts/Navbar.test.js
  src/tests/reducers/notification.test.js
Labels: Ready for Review

#34 164489902 Allowing a user to bookmark an article
  src/actions/bookmarkArticle.js
  src/actions/types.js
  src/assets/css/main.css
  src/assets/scss/_article.scss
  src/components/articles/SingleArticle.js
  src/components/users/profile/ViewProfile.js
  src/reducers/article.js
  src/tests/actions/alert.test.js
  src/tests/actions/bookmarkArticle.test.js
  src/tests/components/articles/SingleArticle.test.js
  src/tests/components/comment/CommentForm.test.js
  src/tests/components/users/authenticate/Authenticate.test.js
  src/tests/reducers/articles/Article.test.js
Labels: Done

#38 #164489907 track comment history
  src/actions/comment/editedComments.js
  src/actions/types.js
  src/components/comment/CommentItem.js
  src/components/comment/CreateComment.scss
  src/reducers/comment/editedComments.js
  src/reducers/index.js
  src/tests/actions/comment/editedComment.test.js
  src/tests/components/comment/CommentItem.test.js
  src/tests/reducers/comments/editedComment.test.js
Labels: Ready for Review

#41 #164489899 Opt in and out of notifications
  src/actions/bookmarkArticle.js
  src/actions/subscribtion.js
  src/actions/types.js
  src/assets/css/main.css
  src/assets/scss/_navbar.scss
  src/components/layouts/Navbar.js
  src/reducers/index.js
  src/reducers/subscribtion.js
  src/tests/actions/subcribtion.test.js
  src/tests/components/layouts/Navbar.test.js
  src/tests/reducers/subscribtion.test.js
Labels: Ready for Review

#36 #164489900 search functionalities
  package.json
  src/App.js
  src/actions/search.js
  src/actions/types.js
  src/assets/css/main.css
  src/assets/scss/_Index.scss
  src/assets/scss/_navbar.scss
  src/assets/scss/_notFound.scss
  src/assets/scss/_search.scss
  src/assets/scss/_singleUser.scss
  src/assets/scss/_style.scss
  src/assets/scss/main.scss
  src/components/Index.js
  src/components/articles/CreateArticle.js
  src/components/articles/EditArticle.js
  src/components/articles/SingleArticle.js
  src/components/layouts/Layout.js
  src/components/layouts/Navbar.js
  src/components/search/AllSearch.js
  src/components/search/Search.js
  src/components/search/ViewSingleUser.js
  src/components/users/profile/ViewBookmarks.js
  src/reducers/index.js
  src/reducers/search.js
  src/routes/routes.js
  src/tests/actions/search.test.js
  src/tests/components/comment/VoteComent.test.js
  src/tests/components/layouts/Navbar.test.js
  src/tests/components/search/AllSearch.test.js
  src/tests/components/search/ViewSingleUser.test.js
  src/tests/components/search/search.test.js
  src/tests/components/users/profile/ViewBookmarks.test.js
  src/tests/reducers/search/search.test.js
Labels: Ready for Review, WIP

#44 #164489897 Follow and unfollow users
  src/App.js
  src/actions/types.js
  src/actions/user/followUser.js
  src/assets/css/main.css
  src/assets/scss/_article.scss
  src/assets/scss/_notFound.scss
  src/components/articles/SingleArticle.js
  src/components/layouts/Navbar.js
  src/components/users/profile/Followers.js
  src/components/users/profile/Followers.scss
  src/components/users/profile/Following.js
  src/reducers/index.js
  src/reducers/users/followUser.js
  src/routes/routes.js
  src/tests/actions/users/folloUser.test.js
  src/tests/components/articles/SingleArticle.test.js
  src/tests/reducers/users/followUser.test.js
Labels: Ready for Review

#46 #166813013 Show a spinner on logging
  package.json
  src/actions/login.js
  src/actions/rateArticle.js
  src/actions/types.js
  src/assets/css/main.css
  src/assets/scss/_button.scss
  src/assets/scss/_config.scss
  src/assets/scss/_form.scss
  src/assets/scss/_starRating.scss
  src/components/articles/rating/Rating.js
  src/components/users/login/Login.js
  src/reducers/login.js
  src/tests/components/actions/login.test.js
  src/tests/components/rating/rating.test.js
  src/tests/components/reducers/login.test.js
  src/tests/components/users/login/Login.test.js
Labels: Ready for Review

#45 #166813438 fix navbar
  src/App.js
  src/assets/css/main.css
  src/assets/scss/_form.scss
  src/assets/scss/_navbar.scss
  src/assets/scss/_profile.scss
  src/assets/scss/_style.scss
  src/components/layouts/Navbar.js
  src/components/users/authenticate/Authenticate.js
  src/routes/routes.js
  src/tests/components/users/authenticate/Authenticate.test.js
  src/tests/components/users/profile/ViewBookmarks.test.js
Labels: Ready for Review

#47 #166866665 modify profile page
  src/assets/css/main.css
  src/assets/scss/_style.scss
  src/components/users/profile/ViewBookmarks.js
  src/components/users/profile/ViewProfile.js
  src/reducers/fetchBookmark.js
  src/tests/reducers/fetchBookmark.test.js
Labels: Ready for Review

#49 #166866764 Fix follow user Feature
  src/components/articles/SingleArticle.js
  src/components/users/profile/Followers.js
  src/components/users/profile/Followers.scss
  src/components/users/profile/Following.js
Labels: Ready for Review

#48 #166866916 close modals
  package.json
  src/App.js
  src/assets/css/main.css
  src/assets/scss/_Index.scss
  src/assets/scss/_article.scss
  src/assets/scss/_navbar.scss
  src/assets/scss/_style.scss
  src/components/layouts/Layout.js
  src/components/layouts/Navbar.js
  src/tests/components/layouts/Layout.test.js
  src/tests/components/layouts/Navbar.test.js
Labels: Ready for Review

#50 #166838392 show the count of the users who reported a certain article
  package.json
  src/assets/css/main.css
  src/assets/scss/_reportArticle.scss
  src/components/articles/SingleArticle.js
  src/components/articles/reporting/ReportArticle.js
  src/components/articles/reporting/ReportedArticles.js
  src/tests/components/reporting/ReportedArticles.test.js
Labels: Ready for Review

#52 154489893 pagination support for articles
  src/actions/article.js
  src/assets/css/main.css
  src/assets/scss/_Index.scss
  src/assets/scss/_article.scss
  src/assets/scss/_auth.scss
  src/assets/scss/_style.scss
  src/components/Index.js
  src/components/users/authenticate/Authenticate.js
  src/reducers/article.js
  src/tests/actions/article.test.js
  src/tests/components/articles/AllArticle.test.js
  src/tests/reducers/articles/Article.test.js
Labels: Ready for Review

#51 166838503 Adding a spinner on the reading a single article.
  package.json
  src/components/articles/SingleArticle.js
Labels: Ready for Review
